### ISSUE TITLE
SyntaxError since last update (25/11/23) 

### ISSUE THREAD

**Issue by JordanOllivier** [fmartinou/tydom2mqtt#156] opened 2023-11-26 15:56 UTC
Hi ! 

Since the last update, i've got an issue on reload. 

SyntaxError: unterminated string literal (detected at line 58)
Traceback (most recent call last):
  File "/app/main.py", line 10, in <module>
    from mqtt.MqttClient import MqttClient
  File "/app/mqtt/MqttClient.py", line 13, in <module>
    from sensors.Light import Light
  File "/app/sensors/Light.py", line 58
    'state_value_template: "{{ 'ON' if value | int(0) > 0 else 'OFF

![Screenshot_20231126_165424_Chrome](https://github.com/fmartinou/tydom2mqtt/assets/5736088/f8af8b44-189c-4bee-90fa-743097f51c94)

**Comment by birse29** [comment] 2023-11-26 16:45
Hello,

Same issue with last update

**Comment by Coldness00** [comment] 2023-11-26 16:50
Hello Dears,
Same, I went back to the previous image

**Comment by BlacKTM1190** [comment] 2023-11-27 08:34
Hello,
There's missing a quote between `state_value_template` and `:` in #145 line 58.
See #157

**Comment by fmartinou** [comment] 2023-11-30 06:28
Thanks for the fix; the PR has been merged.

**Closed by fmartinou** 2023-11-30 06:28 UTC

**Comment by Coldness00** [comment] 2023-11-30 13:24
Hello,
Sorry, on my side the issue is still present after pulling latest image :/

![image](https://github.com/fmartinou/tydom2mqtt/assets/13046218/41604478-bdcd-4c77-9a58-11a22998df80)

**Comment by fmartinou** [comment] 2023-11-30 15:18
Now this is a missing comma 😤 ; I fix it

**Comment by fmartinou** [comment] 2023-12-01 15:23
Thanks for the feedback; I'll build a new release with fixes asap.
