### ISSUE TITLE
Installation de la version 2.3.0

### ISSUE THREAD

**Issue by LGO44** [fmartinou/tydom2mqtt#35] opened 2022-09-05 19:31 UTC
HACS ne détecte pas cette nouvelle version?
j'ai essaye de rajouter l'integration via HACS j'obtiens le message : 
<Integration fmartinou/tydom2mqtt> Repository structure for 2.3.0 is not compliant

**Comment by LGO44** [comment] 2022-09-06 10:36
Après installation de la version 2.3.0 depuis "Fmartinou add-ons" 

1. l'integration ne crée plus les volets 
2. Les binary_sensor ne sont pas mis a jour

extrait du fichier log:

_2022-09-06 12:26:17.263 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Chambre 1', 'unique_id': '1651773567_1651773567', 'command_topic': 'cover/tydom/1651773567_1651773567/set_positionCmd', 'set_position_topic': 'cover/tydom/1651773567_1651773567/set_position', 'json_attributes_topic': 'cover/tydom/1651773567_1651773567/attributes', 'payload_open': 'UP', 'payload_close': 'DOWN', 'payload_stop': 'STOP', 'retain': 'false', 'device': {'manufacturer': 'Delta Dore', 'model': 'Volet', 'name': 'Chambre 1', 'identifiers': '1651773567_1651773567'}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 123, in validate_options
    raise vol.Invalid(
voluptuous.error.Invalid: 'set_position_topic' must be set together with 'position_topic'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 323, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: 'set_position_topic' must be set together with 'position_topic'._

2022-09-06 12:26:17.290 INFO (MainThread) [homeassistant.components.mqtt.mixins] Got update for entity with hash: ('sensor', 'tydom device_id_tydom_1651773567_1651773567') '{'name': 'device_id_tydom__Chambre_1', 'unique_id': 'device_id_tydom_1651773567_1651773567', 'device': {'manufacturer': 'Delta Dore', 'model': 'Sensor', 'name': 'device_id_tydom__Chambre_1', 'identifiers': '1651773567_1651773567_sensors'}, 'state_topic': 'sensor/tydom/device_id_tydom_1651773567_1651773567/state', 'platform': 'mqtt'}'
2022-09-06 12:26:17.291 INFO (MainThread) [homeassistant.components.mqtt.mixins] Ignoring unchanged update for: sensor.device_id_tydom_chambre_1
2022-09-06 12:26:17.292 INFO (MainThread) [homeassistant.components.mqtt.mixins] Got update for entity with hash: ('sensor', 'tydom endpoint_id_tydom_1651773567_1651773567') '{'name': 'endpoint_id_tydom__Chambre_1', 'unique_id': 'endpoint_id_tydom_1651773567_1651773567', 'device': {'manufacturer': 'Delta Dore', 'model': 'Sensor', 'name': 'endpoint_id_tydom__Chambre_1', 'identifiers': '1651773567_1651773567_sensors'}, 'state_topic': 'sensor/tydom/endpoint_id_tydom_1651773567_1651773567/state', 'platform': 'mqtt'}'
2022-09-06 12:26:17.292 INFO (MainThread) [homeassistant.components.mqtt.mixins] Ignoring unchanged update for: sensor.endpoint_id_tydom_chambre_1

**Comment by fmartinou** [comment] 2022-09-06 11:34
I close this issue because it'is a duplicate of #34 .

**Closed by fmartinou** 2022-09-06 11:34 UTC
